# NumPy

In [1]:
import numpy as np

In [2]:
np?

Type:        module
String form: <module 'numpy' from '/home/francisco/.local/lib/python3.8/site-packages/numpy/__init__.py'>
File:        ~/.local/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x 

In [3]:
#array
numeros = np.array([1,2,3,4,5])

In [4]:
numeros

array([1, 2, 3, 4, 5])

In [5]:
type(numeros)

numpy.ndarray

In [6]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
   

In [7]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([x for x in range(1,11,2)])

array([1, 3, 5, 7, 9])

In [18]:
enteros = np.array([[1, 2,3,4,5,6], [3, 4,5,6,7,8]])

In [16]:
floats = np.array([0.00000, 0.1, 0.2, 0.3, 1.0, 1])

In [17]:
floats

array([0. , 0.1, 0.2, 0.3, 1. , 1. ])

In [19]:
enteros.dtype

dtype('int64')

In [20]:
floats.dtype

dtype('float64')

In [21]:
enteros.ndim

2

In [22]:
enteros

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]])

In [23]:
floats.ndim

1

In [24]:
enteros.shape

(2, 6)

In [25]:
floats.shape

(6,)

In [26]:
enteros.size

12

In [27]:
floats.size

6

In [28]:
enteros.itemsize

8

In [30]:
for fila in enteros:
    print(fila)

[1 2 3 4 5 6]
[3 4 5 6 7 8]


In [29]:
for fila in enteros:
    for col in fila:
        print(col, end=' ')
    print()

1 2 3 4 5 6 
3 4 5 6 7 8 


In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.full((3,5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

# arange

In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [37]:
np.arange(10,100,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

# linspace

In [41]:
np.linspace(0,30, num=10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [44]:
np.linspace(0,1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [49]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
np.arange(1,100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [52]:
np.arange(1,100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [53]:
#midiendo tiempo con %timeit

In [54]:
import random

In [55]:
%timeit dados = [random.randrange(1,7) for i in range(0, 6000000)]

3.54 s ± 66.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
%timeit dados = np.random.randint(1,7,6000000)

62.2 ms ± 480 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [58]:
numeros * 4

array([ 4,  8, 12, 16, 20])

In [59]:
[ 4,  8, 12, 16, 20] * 4

[4, 8, 12, 16, 20, 4, 8, 12, 16, 20, 4, 8, 12, 16, 20, 4, 8, 12, 16, 20]

In [61]:
valores = numeros ** 2

In [62]:
valores

array([ 1,  4,  9, 16, 25])

In [65]:
l = []
for i in range(10):
    a = i+1
    l.append(a)

In [67]:
l = [a+1 for a in range(10)]

In [72]:
numeros /0.0000001

array([1.1e+08, 1.2e+08, 1.3e+08, 1.4e+08, 1.5e+08])

In [70]:
numeros += 10

In [71]:
numeros

array([11, 12, 13, 14, 15])

In [73]:
numeros

array([11, 12, 13, 14, 15])

In [74]:
n = np.array([1,2,3,4,5])

In [75]:
numeros + n

array([12, 14, 16, 18, 20])

In [76]:
numeros * n

array([11, 24, 39, 56, 75])

In [77]:
numeros == n

array([False, False, False, False, False])

In [78]:
numeros * np.array([1,2,3,4,5,6,7,8])

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [79]:
np.arange(1,6) ** 2

array([ 1,  4,  9, 16, 25])